import { calcSubtotal, calcTotal, escapeHtml, formatDate, formatPrice } from './utils.js';

export const ICONS = {
  back:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg>',
  settings:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82..."/></svg>',
  plus:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>',
  trash:'🗑️', copy:'📄', pdf:'PDF', save:'💾', search:'🔎'
};

export function renderHome(state, search='') { const list=state.presupuestos.slice().sort((a,b)=>(b.fecha||'').localeCompare(a.fecha||'')); const q=search.toLowerCase(); const f=!q?list:list.filter(p=>((p.cliente&&p.cliente.nombre)||'').toLowerCase().includes(q)||String(p.numero||'').includes(q));
const cards=f.length?'<div class="card-list">'+f.map(p=>`<div class="card" data-open="${p.id}"><div class="card-num">Nº ${String(p.numero).padStart(3,'0')}</div><div class="card-main"><div class="card-title">${escapeHtml((p.cliente&&p.cliente.nombre)||'(Sin nombre)')}</div><div class="card-meta">${escapeHtml(formatDate(p.fecha))} · ${escapeHtml((p.cliente&&p.cliente.localidad)||'')}</div></div><div class="card-amount">${formatPrice(calcTotal(p))}€</div></div>`).join('')+'</div>':'<div class="empty-state"><p><strong>Aún no hay presupuestos</strong></p></div>';
return `<header class="header"><h1>Presupuestos</h1><button class="icon-btn" data-action="settings">⚙️</button></header><main class="content">${list.length?`<div class="search-box"><input type="search" data-search value="${escapeHtml(search)}" /></div>`:''}${cards}</main><footer class="bottom-bar"><button class="btn btn-primary" data-action="new"><span class="btn-plus" aria-hidden="true">+</span> Nuevo presupuesto</button></footer>`; }

export function renderEditor(state,draft){ const subtotal=calcSubtotal(draft), total=calcTotal(draft); const isNew=!state.presupuestos.find(x=>x.id===draft.id); const lineas=(draft.lineas||[]).map((l,i)=>`<div class="line-item"><div class="line-item-header"><span class="num">${i+1}</span><span>Concepto</span><span class="spacer"></span>${draft.lineas.length>1?`<button class="line-remove" title="Eliminar línea" data-remove-line="${i}">${ICONS.trash}</button>`:''}</div><textarea class="textarea" data-line-field="descripcion" data-idx="${i}" placeholder="Describe el trabajo">${escapeHtml(l.descripcion||'')}</textarea><div class="price-input"><input class="input" type="number" data-line-field="precio" data-idx="${i}" value="${l.precio??''}" placeholder="Precio"/></div></div>`).join('');
return `<header class="header"><button class="icon-btn" data-action="back">←</button><h1>${isNew?'Nuevo presupuesto':'Presupuesto Nº '+String(draft.numero).padStart(3,'0')}</h1></header><main class="content"><section class="section"><div class="section-header">Datos del cliente</div><div class="section-body"><div class="row"><div class="field"><label>Nombre</label><input class="input" data-field="cliente.nombre" value="${escapeHtml((draft.cliente&&draft.cliente.nombre)||'')}"/></div><div class="field"><label>Fecha</label><input class="input" type="date" data-field="fecha" value="${escapeHtml(draft.fecha||'')}"/></div></div><div class="row"><div class="field"><label>Dirección</label><input class="input" data-field="cliente.direccion" value="${escapeHtml((draft.cliente&&draft.cliente.direccion)||'')}"/></div><div class="field"><label>Localidad</label><input class="input" data-field="cliente.localidad" value="${escapeHtml((draft.cliente&&draft.cliente.localidad)||'')}"/></div></div><div class="field"><label>DNI (opcional)</label><input class="input" data-field="cliente.dni" value="${escapeHtml((draft.cliente&&draft.cliente.dni)||'')}"/></div></div></section><section class="section"><div class="section-header">Líneas del presupuesto</div><div class="section-body">${lineas}<button class="add-line-btn" data-action="add-line"><span class="btn-plus" aria-hidden="true">+</span> Añadir línea</button></div></section><section class="section"><div class="section-header">Notas</div><div class="section-body"><textarea class="textarea" data-field="notas" placeholder="Condiciones de pago...">${escapeHtml(draft.notas||'')}</textarea></div></section><div class="total-card"><div><div class="label">Total</div>${draft.ivaActivo?`<div style="font-size:12px">Subtotal ${formatPrice(subtotal)}€ + IVA ${draft.ivaPorcentaje}%</div>`:''}</div><div class="amount">${formatPrice(total)}€</div></div></main><footer class="bottom-bar"><button class="btn btn-secondary" data-action="save">Guardar</button><button class="btn btn-primary" data-action="pdf">Generar PDF</button></footer>`; }

export function renderSettings(state){const s=state.settings; return `<header class="header"><button class="icon-btn" data-action="back">←</button><h1>Ajustes</h1></header><main class="content"><input class="input" data-setting="emisor.telefono" value="${escapeHtml(s.emisor.telefono||'')}" /><textarea class="textarea" data-setting="notasDefecto">${escapeHtml(s.notasDefecto||'')}</textarea><button class="btn btn-secondary" data-action="export">Exportar</button><button class="btn btn-secondary" data-action="import">Importar</button><button class="btn btn-danger" data-action="reset">Borrar todos los presupuestos</button></main>`;}
